"""Local execution tracing for the two-arm task APIs.

The wrapper is deliberately opt-in at the API boundary so shared execution
infrastructure and non-two-arm tasks keep their existing behaviour.
"""

from __future__ import annotations

import functools
import inspect
from typing import Any, Callable


class TwoArmExecutionTraceMixin:
    """Wrap public API functions with Web UI step and MuJoCo-frame logging."""

    def _trace_functions(self, functions: dict[str, Callable[..., Any]]) -> dict[str, Callable[..., Any]]:
        wrapped: dict[str, Callable[..., Any]] = {}
        for name, function in functions.items():
            wrapped[name] = function if getattr(function, "_two_arm_traced", False) else self._trace_function(name, function)
        return wrapped

    def _trace_function(self, name: str, function: Callable[..., Any]) -> Callable[..., Any]:
        @functools.wraps(function)
        def traced(*args: Any, **kwargs: Any) -> Any:
            if not getattr(self, "_webui_enabled", False):
                return function(*args, **kwargs)

            try:
                call = inspect.signature(function).bind(*args, **kwargs)
                call.apply_defaults()
                details = ", ".join(
                    f"{key}={_format_value(value)}" for key, value in call.arguments.items()
                )
            except Exception:
                details = ""
            self._log_step(name, f"Executing `{name}`" + (f" ({details})" if details else ""))
            try:
                result = function(*args, **kwargs)
            except Exception as exc:
                self._log_step_update(text=f"Failed: {type(exc).__name__}: {exc}")
                raise

            frame = _capture_frame(self._env)
            self._log_step_update(text="Completed.", images=frame)
            return result

        traced._two_arm_traced = True  # type: ignore[attr-defined]
        return traced


def _format_value(value: Any) -> str:
    if hasattr(value, "shape"):
        try:
            return f"array(shape={tuple(value.shape)}, values={value.tolist()})"
        except Exception:
            return f"array(shape={value.shape})"
    return repr(value)


def _capture_frame(env: Any) -> Any:
    """Capture all frames generated by this API call for step-by-step playback."""
    try:
        if hasattr(env, "get_video_frames"):
            frames = env.get_video_frames(clear=False)
            if frames:
                return frames[- min(len(frames), 24) :]
        if hasattr(env, "render"):
            return env.render(mode="rgb_array")
    except Exception:
        return None
    return None
